### ISSUE TITLE
Auto-FCS Transmission is not handled

### ISSUE THREAD

**Issue by Beetix** [Decawave/mynewt-dw1000-core#31]
The function [dw1000_write_tx](https://github.com/Decawave/mynewt-dw1000-core/blob/d6b1414f1b4527abda7521a304baa1c648244108/hw/drivers/uwb/uwb_dw1000/src/dw1000_mac.c#L477) does not handle auto-FCS transmission. In the current implementation TX frame length does not include the length of the CRC from auto-FCS transmission. I suppose the use case of suppressing auto-FCS transmission is not common so the quickest fix would be to add the length of the CRC from auto-FCS transmission (2 bytes) as in [dw1000_write_tx_fctrl](https://github.com/Decawave/mynewt-dw1000-core/blob/d6b1414f1b4527abda7521a304baa1c648244108/hw/drivers/uwb/uwb_dw1000/src/dw1000_mac.c#L517). If handling Auto-FCS Transmission suppression really has an application a check of the SFCST field from the System Control Register is required.

**Comment by ncasaril** [comment]
You don't actually need to write the two FCS bytes to the device. As long as they're included in the frame length programmed by dw1000_write_tx_fctrl they will be calculated and sent.

**Comment by Beetix** [comment]
What I meant with this issue is that the suppression of Auto-FCS transmission is not handled. An example would be if a user wants to compute his own CRC and doesn't want the one from the transceiver.

**Comment by ncasaril** [comment]
Ok, I see what you mean. The workaround is that the caller can add the 2 bytes to the length of the frame to write the additional FCS bytes using uwb_write_tx. 

I've not yet seen an application where the FCS bytes are not computed by the device. Do you know of one?
The closest I can think of is lossy streaming, where you deliberately don't use the auto-FCS because you're writing the data after start_tx has been issued and only want the frame to be considered valid if you manage to finish writing the frame before the device reads the last bytes in the buffer.

**Comment by Beetix** [comment]
I currently don't have a use case for suppressing the auto-FCS transmission. I just wanted to point it out to be clear.
